version: "3" 

services:
  drupal:
    build:
      context: .
      dockerfile: ./Dockerfile 
    container_name: scmspc-drupal
    ports:
      - 8080:8080
    volumes:
    # For local development, you can map a local directory to the image instead of using the volume
    #  - <your local dev directory>:/opt/app-root/src/data/sites/default/
      - /Users/x/Desktop/InProgress/ISED/workspace/scmspc/scmspc-module:/opt/app-root/src/data/sites/default/modules/ised/
      - /Users/x/Desktop/InProgress/ISED/workspace/scmspc/scmspc-theme:/opt/app-root/src/data/sites/default/themes/ised/
      - scmspc-drupal-data:/opt/app-root/src/data
    env_file:
      - .env
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      LANGUAGE: C.UTF-8
  postgres: 
    image: registry.apps.dev.ocp-dev.ised-isde.canada.ca/ised-ci/ised-postgresql:9.6  
    container_name: smcspc-postgres
    ports:
      - 5432:5432
    volumes:
      - scmspc-postgres-database:/var/lib/pgsql/data 
    environment:
      POSTGRESQL_USER: $POSTGRESQL_USER
      POSTGRESQL_PASSWORD: $POSTGRESQL_PASSWORD
      POSTGRESQL_DATABASE: $POSTGRESQL_DATABASE
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_S3_BUCKET: $AWS_S3_BUCKET
      AWS_S3_REGION: $AWS_S3_REGION
      PATH: $PATH:/tmp
    env_file:
    - .env
  portainer:
      image: portainer/portainer
      container_name: scmspc_portainer
      command: -H unix:///var/run/docker.sock
      restart: always
      ports:
        - 9000:9000
        - 8000:8000
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - scmspc-portainer-data:/data
volumes:
  scmspc-drupal-data:
    external: true
  scmspc-postgres-database:
    external: true
  scmspc-portainer-data:

